### ISSUE TITLE
Missing mod and needed mods

### ISSUE THREAD

**Issue by katelinlis** [SeqTeam0/Sequentialis#1]
mod Applied Energistics 2 missing 
and needed  for chunk loader

refined Storage craft is easy

**Comment by SeqTeam0** [comment]
My bad, didn't see ae2 wasn't in the pack.
Fixed in V. 0.1.8b-fix, also changed forge to 36.2.34

Refined storage and other recipes will change in V. 0.1.9,
Thanks for the support!
